sonar.projectKey=kakabi-christian_PortFolio
sonar.organization=kakabi-christian
# Sources à analyser
sonar.sources=Backend

# Exclusions pour éviter de scanner les bibliothèques externes
sonar.exclusions=**/vendor/**, **/node_modules/**, **/dist/**, **/storage/**, **/public/**
############################################################################################3